In [12]:
import numpy as np
from itertools import combinations

In [28]:
# Create the board and number each box from 1 to 49
board = np.zeros((7,7))

counter =0
for i in range(0, 7):
    for j in range(0,7):
        counter = counter + 1
        board[i,j] = counter

print('Game board:\n', board)

# Initialize a list named sets. This holds every single set that we're dealing with.
sets = []

# Create the set of all regions. This has to be done manually.
sets.append(np.array([board[1,1], board[1,2], board[2,1], board[2,2], board[3,1], board[4,1]]))
sets.append(np.array([board[5,1], board[5,2]]))
sets.append(np.array([board[3,2], board[4,2], board[4,3], board[5,3]]))
sets.append(np.array([board[3,4], board[3,5], board[4,4], board[4,5], board[5,4], board[5,5]]))
sets.append(np.array([board[1,3], board[1,4], board[1,5], board[2,3], board[2,4], board[2,5], board[3,3]]))

# Create the set of all rows
for i in range(1, 6):
    sets.append(board[i,1:6])

# Create the set of all columns
for i in range(1, 6):
    sets.append(board[1:6,i])

# create the set of all 3x3 matrices of each square and its surrounding squares
for i in range(1,6):
    for j in range(1,6):
        sets.append(np.array([board[i-1,j-1], board[i-1,j], board[i-1,j+1], board[i,j-1], board[i,j], board[i,j+1], board[i+1,j-1], board[i+1,j], board[i+1,j+1]]))

# Print all of the surrounding matrices including the number in the center
for i in range(15,len(sets)):
    print('\nSurrounding tiles with',  sets[i][4], ' in the center:\n',sets[i])
    
test = [1, 2, 3, 4]

count2 = 0
for i in range(0,9):
    for j in range(0,9):
        if j<i:
            count2 = count2+1
            print(sets[15][j], sets[15][i])

            print(len(sets))
        

Game board:
 [[ 1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19. 20. 21.]
 [22. 23. 24. 25. 26. 27. 28.]
 [29. 30. 31. 32. 33. 34. 35.]
 [36. 37. 38. 39. 40. 41. 42.]
 [43. 44. 45. 46. 47. 48. 49.]]

Surrounding tiles with 9.0  in the center:
 [ 1.  2.  3.  8.  9. 10. 15. 16. 17.]

Surrounding tiles with 10.0  in the center:
 [ 2.  3.  4.  9. 10. 11. 16. 17. 18.]

Surrounding tiles with 11.0  in the center:
 [ 3.  4.  5. 10. 11. 12. 17. 18. 19.]

Surrounding tiles with 12.0  in the center:
 [ 4.  5.  6. 11. 12. 13. 18. 19. 20.]

Surrounding tiles with 13.0  in the center:
 [ 5.  6.  7. 12. 13. 14. 19. 20. 21.]

Surrounding tiles with 16.0  in the center:
 [ 8.  9. 10. 15. 16. 17. 22. 23. 24.]

Surrounding tiles with 17.0  in the center:
 [ 9. 10. 11. 16. 17. 18. 23. 24. 25.]

Surrounding tiles with 18.0  in the center:
 [10. 11. 12. 17. 18. 19. 24. 25. 26.]

Surrounding tiles with 19.0  in the center:
 [11. 12. 13. 18. 19. 20. 25. 26. 27.]

Surrounding t

In [7]:
sets[15][1,1]

9.0